grails-app/controllers/com/mbds/grails/DashboardController.groovy
package com.mbds.grails

import Forms.Classes.SearchDaysFilter
import Forms.Classes.SearchDowFilter
import Forms.Classes.SearchMonthFilter
import Forms.Classes.TopAuthorsFilter
import grails.converters.JSON
import grails.plugin.springsecurity.annotation.Secured

@Secured(['ROLE_ADMIN', 'ROLE_MODO'])
class DashboardController {

    DashboardService dashboardService

    def index() {
        [current_date: new Date()]
    }

    def statistiques(){
        render dashboardService.statistiques() as JSON
    }
    def articlesParMois(){
        SearchMonthFilter searchMonthFilter = new SearchMonthFilter(params.year)
        def map = [filters: searchMonthFilter,stats: this.dashboardService.nombreArticlesParMois(searchMonthFilter)]
        render map as JSON
    }

    //Articles par jour de la semaine , dow = day of week
    def articlesParDow(){
        SearchDowFilter searchDowFilter = new SearchDowFilter(params.year,params.month)
        def map = [filters: searchDowFilter,stats: this.dashboardService.nombreArticlesParJourDeLaSemaine(searchDowFilter)]
        render map as JSON
    }


    def articlesParJour(){
        SearchDaysFilter searchDaysFilter = new SearchDaysFilter(params.d1,params.d2)
        def map = [filters: searchDaysFilter,stats: this.dashboardService.nombreArticlesParJour(searchDaysFilter)]
        render map as JSON
    }

    def topAuthors(){
        TopAuthorsFilter topAuthorsFilter = new TopAuthorsFilter(params.top,params.month)
        def map = [filters: topAuthorsFilter,stats: this.dashboardService.topUtilisateurs(topAuthorsFilter)]
        render map as JSON
    }
}

grails-app/controllers/com/mbds/grails/GalleryController.groovy
package com.mbds.grails

import Forms.Classes.GallerySearchFilter
import grails.converters.JSON
import grails.orm.PagedResultList
import grails.plugin.springsecurity.annotation.Secured

@Secured(['ROLE_ADMIN', 'ROLE_MODO'])
class GalleryController {
    CustomUserService customUserService
    CustomIllustrationService customIllustrationService

    def index() {
        return
    }
    def searchAuthors(){
        render customUserService.getAuthors(params.keyword) as JSON
    }

    def search(){
        def jsonObject = request.JSON
        GallerySearchFilter gallerySearchFilter = new GallerySearchFilter(jsonObject.keyword,
                jsonObject.authors,
                jsonObject.d1 ? jsonObject.d1 : "",
                jsonObject.d2 ? jsonObject.d2 : "",
                jsonObject.order,
                jsonObject.galleryDate ? "true": "false",
                jsonObject.page ? "" + jsonObject.page : 1)

        PagedResultList resultat = customIllustrationService.search(gallerySearchFilter,10)
        def map = [pages: UtilService.getPageNumbers(resultat.totalCount.intValue(),10),
                   currentpage: gallerySearchFilter.page,
                   data: resultat,
                   params:gallerySearchFilter]
        render map as JSON
    }
}

grails-app/views/shared/_navbar.gsp
<g:set var="current_user" value="${request.getAttribute("current_user")}" />
<nav class="layout-navbar navbar navbar-expand-lg align-items-lg-center bg-dark container-p-x" id="layout-navbar">

    <!-- Brand demo (see assets/css/demo/demo.css) -->
    <a href="index.html" class="navbar-brand app-brand demo d-lg-none py-0 mr-4">
        <span class="app-brand-text demo font-weight-normal ml-2">Empire</span>
    </a>

    <!-- Sidenav toggle (see assets/css/demo/demo.css) -->
    <div class="layout-sidenav-toggle navbar-nav d-lg-none align-items-lg-center mr-auto">
        <a class="nav-item nav-link px-0 mr-lg-4" href="javascript:">
            <i class="ion ion-md-menu text-large align-middle"></i>
        </a>
    </div>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#layout-navbar-collapse">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="navbar-collapse collapse" id="layout-navbar-collapse">
        <!-- Divider -->
        <hr class="d-lg-none w-100 my-2">
        <g:form controller="annonce" action="index" name="searchForm" method="get" class="tm-contact-form">
            <div class="navbar-nav align-items-lg-center">
                <!-- Search -->
                <label class="nav-item navbar-text navbar-search-box p-0 active">
                    <button style="background-color: white;" type="submit" class="btn btn-prinary" name="submit">
                        <i class="feather icon-search navbar-icon align-middle"></i>
                    </button>
                    <span class="navbar-search-input pl-2">
                        <input type="text" id="search"
                               class="form-control navbar-text mx-2 searchInput"
                               value="${keyword_annonce ? keyword_annonce : ''}" name="search" placeholder="rechercher...">
                    </span>
                </label>
            </div>
        </g:form>

        <div class="navbar-nav align-items-lg-center ml-auto">

            <!-- Divider -->
            <div class="nav-item d-none d-lg-block text-big font-weight-light line-height-1 opacity-25 mr-3 ml-1">|</div>
            <div class="demo-navbar-user nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">
                    <span class="d-inline-flex flex-lg-row-reverse align-items-center align-middle">
                        <span class="px-1 mr-lg-2 ml-2 ml-lg-0">${current_user.username}</span>
                    </span>
                </a>
                <div class="dropdown-menu dropdown-menu-right">
                    <div style="width:100%;padding:15px;display: flex;justify-content: center;align-items: center;">
                        <div class="round-user">
                            <i class="fas fa-user"></i>
                        </div>
                    </div>
                    <div class="roles" style="width: 100%">
                        <sec:ifAllGranted roles='ROLE_ADMIN'>
                            <p class="connected_name"
                               style="text-align: center;width:100%;">Administrateur</p>
                        </sec:ifAllGranted>
                        <sec:ifAllGranted roles='ROLE_MODO'>
                            <p class="connected_name"
                               style="text-align: center;width:100%;">Modérateur</p>
                        </sec:ifAllGranted>
                    </div>
                    <div class="dropdown-divider"></div>
                    <g:link controller="user" action="logout" class="link">
                        <i class="feather icon-power text-danger"></i> Déconnexion
                    </g:link>
                    <g:link controller="user" action="configuration" class="link">
                        <i class="fas fa-cog text-danger"></i> Configuration
                    </g:link>
            </div>
        </div>
    </div>
</nav>

grails-app/views/shared/_sidenav.gsp
<div id="layout-sidenav" class="layout-sidenav sidenav sidenav-vertical bg-white logo-dark">
    <!-- Brand demo (see assets/css/demo/demo.css) -->
    <div class="app-brand demo">
        <a href="index.html" class="app-brand-text demo sidenav-text font-weight-normal ml-2">E-Annonce</a>
    </div>
    <div class="sidenav-divider mt-0"></div>

    <!-- Links -->
    <ul class="sidenav-inner py-1">

        <!-- Dashboards -->
        <li class="sidenav-item active">

            <g:link controller="dashboard" class="sidenav-link" action="index">
                <i class="sidenav-icon  fas fa-chart-area"></i>
                <div>Tableau de bord</div>
            </g:link>
        </li>

        <!-- UI elements -->
        <li class="sidenav-item">
            <a href="javascript:" class="sidenav-link sidenav-toggle">
                <i class="sidenav-icon  fas fa-pen-square"></i>
                <div>Annonces</div>
            </a>
            <ul class="sidenav-menu">
                <li class="sidenav-item">
                    <g:link controller="annonce" class="sidenav-link" action="index">
                        <div>Liste</div>
                    </g:link>
                </li>
                <sec:ifAllGranted roles='ROLE_ADMIN'>
                    <li class="sidenav-item">
                        <g:link controller="annonce" class="sidenav-link" action="create">
                            <div>Ajout</div>
                        </g:link>
                    </li>
                </sec:ifAllGranted>
            </ul>
        </li>
        <li class="sidenav-item">
            <a href="javascript:" class="sidenav-link sidenav-toggle">
                <i class="sidenav-icon  fas fa-user"></i>
                <div>Utilisateurs</div>
            </a>
            <ul class="sidenav-menu">
                <li class="sidenav-item">
                    <g:link controller="user" class="sidenav-link" action="index">
                        <div>Liste</div>
                    </g:link>
                </li>
                <sec:ifAllGranted roles='ROLE_ADMIN'>
                    <li class="sidenav-item">
                        <g:link controller="user" class="sidenav-link" action="create">
                            <div>Ajout</div>
                        </g:link>
                    </li>
                </sec:ifAllGranted>
            </ul>
        </li>
        <li class="sidenav-item active">
            <g:link controller="gallery" class="sidenav-link" action="index">
                 <i class="sidenav-icon icon-p fas fa-image"></i>
                 <div>Gallerie</div>
            </g:link>
        </li>
    </ul>
</div>