grails-app/domain/com/mbds/grails/User.groovy
package com.mbds.grails

import groovy.transform.EqualsAndHashCode
import groovy.transform.ToString
import grails.compiler.GrailsCompileStatic

@GrailsCompileStatic
@EqualsAndHashCode(includes='username')
@ToString(includes='username', includeNames=true, includePackage=false)
class User implements Serializable {

    private static final long serialVersionUID = 1

    String username
    String password
    boolean enabled = true
    boolean accountExpired
    boolean accountLocked
    boolean passwordExpired

    static hasMany = [annonces: Annonce]

    Set<Role> getAuthorities() {
        (UserRole.findAllByUser(this) as List<UserRole>)*.role as Set<Role>
    }

    static constraints = {
        password nullable: false, blank: false, password: true
        username nullable: false, blank: false, unique: true
    }

    static mapping = {
	    password column: '`password`'
    }
}

grails-app/controllers/com/mbds/grails/UserController.groovy
package com.mbds.grails

import Forms.Classes.CreateUserForm
import grails.converters.JSON
import grails.plugin.springsecurity.SpringSecurityUtils
import grails.plugin.springsecurity.annotation.Secured
import grails.plugin.springsecurity.userdetails.GrailsUser
import grails.validation.ValidationException

import javax.servlet.http.HttpServletResponse
import java.text.SimpleDateFormat
import org.springframework.web.multipart.MultipartFile
import static org.springframework.http.HttpStatus.*

@Secured(['ROLE_ADMIN', 'ROLE_MODO'])
class UserController {

    UserService userService

    UserRoleService userRoleService
    CustomUserService customUserService
    def springSecurityService

    def exportService

    static allowedMethods = [save: "POST", update: "PUT",configurerPassword: "POST",configurerUsername: "POST"]


    /*@org.springframework.security.access.annotation.Secured('permitAll')*/
    def logout(){
        redirect(uri: SpringSecurityUtils.securityConfig.logout.filterProcessesUrl + "?spring-security-redirect=/login1Page")
    }
    def index() {
        String searchkey = params.searchkey ? params.searchkey : ''
        String status = params.status ? params.status : null
        def users = customUserService.list(params, searchkey, status)
        respond users.list, model:[userCount: users.count,text: searchkey,status: status]
    }

    def export(){
        params.exportFormat = "excel"
        params.extension = "xls"
            def users = User.findAll()
            def result = []
            users.each {a ->
                def map = [:]
                map.put("username", a.username)
                map.put("role", a.authorities.find().authority)
                map.put("accountExpired", a.accountExpired)
                map.put("accountLocked", a.accountLocked)
                map.put("passwordExpired", a.passwordExpired)
                result.add(map)
            }
            response.contentType = grailsApplication.config.grails.mime.types[params.exportFormat]
            response.setHeader("Content-disposition", "attachment; filename=users-"+new SimpleDateFormat("ddMMyyy").format(new Date())+".xls")
            List fields = [
                    "username",
                    "role",
                    "accountExpired",
                    "accountLocked",
                    "passwordExpired",
            ]
            Map labels = ["username": "Nom d'utilisateur", "role": "Rôle", "accountExpired": "Compte expiré", "accountLocked": "Compte bloqué", "passwordExpired": "Mot de passe expiré"]
            Map formatters = [:]
            Map parameters = [:]
            exportService.export(params.exportFormat, response.outputStream, result, fields, labels, formatters, parameters)
    }

    def show(Long id) {
        respond userService.get(id)
    }

    @Secured(['ROLE_ADMIN'])
    def create() {
        [user: new CreateUserForm(), roleList: userRoleService.listRoles()]
    }

    @Secured(['ROLE_ADMIN'])
    def save(){
        def userform = new CreateUserForm(username: params.username,password: params.password,role: params.role)
        try {
            userRoleService.createUser(userform)
            flash.message = "l'utilisateur a été créé"
            redirect action: 'index', controllerName: 'user'
        }
        catch (ValidationException validationException){
            respond view: 'create',userform.errors, model: [user: userform, roleList: userRoleService.listRoles()]
            return
        }
        catch(Exception e){
            flash.message = e.message
            redirect action: 'create', controllerName: 'user'
        }
    }


    def edit(Long id) {
        def user = userService.get(id)
        user.password = ''
        def role = userRoleService.getUserRole(user)
        respond user, model: [roleList: userRoleService.listRoles(),userRole: role]
    }

    def update(User user) {
        if (user == null) {
            notFound()
            return
        }
        def currentUser = springSecurityService.getPrincipal() as GrailsUser
        try {
            user.enabled = params.enabled == "true"
            user.accountLocked = params.accountLocked == "true"
            user.accountExpired = params.accountExpired == "true"
            user.passwordExpired= params.passwordExpired == "true"
            def role = Role.findById(Long.valueOf(params.role))
            user = customUserService.updateUser(user,user.id == currentUser.id,role)
            flash.message = "L'utilisateur a été mis à jour avec succès"
            redirect action: 'edit', controllerName: 'user', id: user.id
        } catch (ValidationException e) {
            respond user.errors, view:'edit',model: ['user': user]
            return
        } catch(Exception e){
            flash.message = e.message
            redirect action: 'edit', controllerName: 'user',id: user.id
        }
    }

    @Secured(['ROLE_ADMIN'])
    def delete(Long id) {
        def user = userService.get(id)
        if (!user) {
            notFound()
            return
        }
        def currentUser = springSecurityService.getPrincipal() as GrailsUser
        try{
            if(user.id == currentUser.id){
                throw new Exception('Vous ne pouvez pas vous supprimer')
            }
            userRoleService.deleteUser(user)
            flash.message =  "L'utilisateur vient d'être supprimé"
            redirect action: 'index', controllerName: 'user'
        }
        catch (Exception e){
            flash.message =  e.message
            redirect action: 'index', controllerName: 'user'
        }
    }


    @Secured(['ROLE_ADMIN'])
    def upload(){
        try{
            userRoleService.uploadCSV(request)
            flash.message = "l'import s'est bien passé"
        }
        catch (Exception e){
            flash.message = "Une erreur est survenue"
        }
        finally {
            redirect(action: 'index')
        }
    }

    protected void notFound() {render status: NOT_FOUND }

    def updateStatusUser() {
        ResultJson resultJson = new ResultJson()
        resultJson.action = null
        resultJson.message = "La mise à jour du status est un succès !"
        resultJson.status = true
        try{
            long idUser = Long.valueOf(params.iduser)
            boolean status = params.boolean('status')
            def user = userService.get(idUser)
            if(!user){
                response.status = HttpServletResponse.SC_NOT_FOUND
                throw new Exception('Utilisateur non existant')
            }
            def currentUser = springSecurityService.getPrincipal() as GrailsUser
            if(user.id == currentUser.id){
                throw new Exception('Vous ne pouvez pas vous bloquer/débloquer')
            }
            user.enabled = status
            userService.save(user)
        }
        catch (Exception e){
            resultJson.message = e.message
            resultJson.status = false
            response.status = HttpServletResponse.SC_BAD_REQUEST
        }
        finally {
            render resultJson as JSON
        }
    }
    def configuration(){
        def user =  springSecurityService.currentUser
        respond user
    }
    def configurerUsername(){
        def currentUser = springSecurityService.currentUser
        def originalName = currentUser.username
        try{
            currentUser.username = params.username
            currentUser = customUserService.configurer(currentUser,false)
            flash.message = "Configuration achevée"
            redirect action: 'configuration'
        }
        catch (ValidationException e){
            currentUser.username = originalName
            respond currentUser.errors, view:'configuration',model: ['user': currentUser]
            return
        }
        catch(Exception e){
            flash.message = e.message
            redirect action: 'configuration', controllerName: 'user'
        }
    }
    def configurerPassword(){
        def currentUser = springSecurityService.currentUser
        try{
            currentUser.password = params.password
            currentUser = customUserService.configurer(currentUser,true)
            flash.message = "Configuration achevée"
            redirect action: 'configuration'
        }
        catch (ValidationException e){
            respond currentUser.errors, view:'configuration',model: ['user': currentUser]
            return
        }
        catch(Exception e){
            flash.message = e.message
            redirect action: 'configuration', controllerName: 'user'
        }
    }

}

grails-app/views/user/configuration.gsp
<%--
  Created by IntelliJ IDEA.
  User: Andi
  Date: 12/03/2021
  Time: 16:06
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<g:set var="current_user" value="${request.getAttribute("current_user")}" />
<html>
<head>
    <meta name="layout" content="main" />
</head>

<body>
<div class="card mb-4">
    <h6 class="card-header">Configurer votre compte</h6>
    <div class="card-body">
        <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
        </g:if>
        <g:form controller="user" action="configurerUsername" method="POST" style="padding-bottom: 15px;">
            <div class="form-group">
                <label class="form-label">Votre nom</label>
                <input type="text" class="form-control" placeholder="Nom" value="${user.username}" name="username">
                <g:renderErrors bean="${user}" as="list" field="username"/>
            </div>
            <button type="submit" class="btn btn-primary">Modifier</button>
        </g:form>
        <g:form controller="user" action="configurerPassword" method="POST" style="padding-bottom: 15px;">
            <div class="form-group">
                <label class="form-label">Votre mot de passe</label>
                <input type="text" class="form-control" placeholder="Mot de passe" value="" name="password">
                <g:renderErrors bean="${user}" as="list" field="password"/>
            </div>
            <button type="submit" class="btn btn-primary">Modifier</button>
        </g:form>
    </div>
</div>

</body>
</html>

grails-app/views/user/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
    <!-- [ Layout content ] Start -->
    <div class="layout-content">

        <!-- [ content ] Start -->
        <div class="container-fluid flex-grow-1 container-p-y">
            <h4 class="font-weight-bold py-3 mb-0">Ajout d'un utilisateur</h4>
            <div class="text-muted small mt-0 mb-4 d-block breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">Utilisateurs</li>
                    <li class="breadcrumb-item active">Ajout</li>
                </ol>
            </div>
        <div class="card mb-4">
            <h6 class="card-header">Utilisateurs</h6>
            <div class="card-body">
                <g:if test="${flash.message}">
                    <div class="message" role="status">${flash.message}</div>
                </g:if>
                <g:form controller="user" action="save" method="POST">
                    <div class="form-group">
                        <label class="form-label">Nom</label>
                        <input type="text" class="form-control"
                               placeholder="Nom"
                               name="username" value="${user.username}">
                        <g:renderErrors bean="${user}" as="list" field="username"/>
                    </div>
                    <div class="form-group">
                        <label class="form-label">Mot de passe</label>
                        <input type="password"
                               class="form-control"
                               placeholder="Mot de passe" name="password" value="${user.password}">
                        <g:renderErrors bean="${user}" as="list" field="password"/>
                    </div>
                    <div class="form-group">
                        <label class="form-label">Role</label>
                        <select class="custom-select" name="role">
                            <option value=""></option>
                            <g:each in="${roleList}" var="role" status="i">
                                <g:if test="${user.role == role.id}">
                                    <option value="${role.id}" selected>${role.authority}</option>
                                </g:if>
                                <g:if test="${user.role != role.id}">
                                    <option value="${role.id}">${role.authority}</option>
                                </g:if>
                            </g:each>
                        </select>
                        <g:renderErrors bean="${user}" as="list" field="role"/>
                    </div>
                    <button type="submit" class="btn btn-primary">Créer</button>
                </g:form>
            </div>
        </div>
        </div>
    </body>
</html>

grails-app/views/user/edit.gsp
<%--
  Created by IntelliJ IDEA.
  User: Andi
  Date: 12/03/2021
  Time: 16:06
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<g:set var="current_user" value="${request.getAttribute("current_user")}" />
<html>
<head>
  <meta name="layout" content="main" />
</head>

<body>
<div class="card mb-4">
  <h6 class="card-header">Modification Utilisateur</h6>
  <div class="card-body">
    <g:if test="${flash.message}">
      <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:form controller="user" action="update" id="${user.id}" method="PUT">
      <div class="form-group">
        <label class="form-label">Nom d'utilisateur</label>
        <input type="text" class="form-control" placeholder="Nom" value="${user.username}" name="username">
        <g:renderErrors bean="${user}" as="list" field="username"/>
      </div>
      <g:if test="${user.id != current_user.id}">
        <div class="form-group">
        <label class="custom-control custom-checkbox">
          <input type="checkbox" value="true" class="custom-control-input" ${user.enabled ? "checked" : "" } name="enabled">
          <span class="custom-control-label">Activer</span>
          <g:renderErrors bean="${user}" as="list" field="enabled"/>
        </label>
      </div>
      <div class="form-group">
        <label class="custom-control custom-checkbox">
          <input type="checkbox" value="true" class="custom-control-input"  ${user.accountExpired ? "checked" : "" } name="accountExpired">
          <span class="custom-control-label">Compte expiré</span>
          <g:renderErrors bean="${user}" as="list" field="accountExpired"/>
        </label>
      </div>
        <div class="form-group">
          <label class="custom-control custom-checkbox">
            <input type="checkbox" value="true" class="custom-control-input"  ${user.accountLocked ? "checked" : "" } name="accountLocked">
            <span class="custom-control-label">Compte vérrouillé</span>
            <g:renderErrors bean="${user}" as="list" field="accountLocked"/>
          </label>
        </div>
        <div class="form-group">
          <label class="custom-control custom-checkbox">
            <input type="checkbox" value="true" class="custom-control-input"  ${user.passwordExpired ? "checked" : "" } name="passwordExpired">
            <span class="custom-control-label">Mot de passe expiré </span>
            <g:renderErrors bean="${user}" as="list" field="passwordExpired"/>
          </label>
        </div>
      </g:if>
      <div class="form-group">
        <label class="form-label">Role</label>
        <select class="custom-select" name="role">
          <option value=""></option>
          <g:each in="${roleList}" var="role" status="i">
            <g:if test="${userRole.id == role.id}">
              <option value="${role.id}" selected>${role.authority}</option>
            </g:if>
            <g:else>
              <option value="${role.id}">${role.authority}</option>
            </g:else>
          </g:each>
        </select>
      </div>
      <button type="submit" class="btn btn-primary">Modifier</button>
      <g:link controller="user" action="show" id="${user.id}">
        <button type="button" class="btn btn-primary">Annuler</button>
      </g:link>
    </g:form>
  </div>
</div>

</body>
</html>

grails-app/views/user/index.gsp
<g:set var="user" value="${request.getAttribute("current_user")}" />
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
        <link rel="stylesheet" href="https://unpkg.com/@egoist/snackbar/dist/snackbar.min.css"/>
    </head>
    <body>
        <div id="list-user" class="content scaffold-list" role="main">
            <h1> Liste des utilisateurs </h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <sec:ifAllGranted roles='ROLE_ADMIN'>
                <div class="export_button" style="display: flex; justify-content: space-between;align-items:center;
                background: white;padding: 5px;">
                    <g:uploadForm controller="user" action="upload" name="searchForm" class="tm-contact-form">
                        <div class="rs-select2--light rs-select2--md">
                            <input id="filecsv" name="filecsv" type="file"/>
                        </div>&nbsp
                        <button class="btn btn-lg btn-outline-primary" style="margin-top: 10px;">Import</button>
                    </g:uploadForm>
                    <div class="export_button" style="display: flex; justify-content: flex-end">
                        <g:link controller="user" action="export" class="btn btn-lg btn-outline-primary">Export</g:link>
                    </div>
                </div>
            </sec:ifAllGranted>
            <g:form controller="user"
                    method="get"
                    action="index"
                    class="form-row mb-1" style="box-shadow:none;background: white;margin-top: 21px;">
                <div class="form-group col-md-4">
                    <input type="text"
                           value="${text}"
                           name="searchkey"
                           class="form-control"
                           placeholder="Recherche">
                </div>
                <div class="form-group col-md-4">
                    <select class="custom-select" id="status" name="status">
                        <option value="" ${status == null ? 'selected': ''}>-- Selectionner status -- </option>
                        <option value="true" ${status == "true" ? 'selected': ''}>Actif</option>
                        <option value="false" ${status == "false" ? 'selected': ''}>Inactif</option>
                    </select>
                </div>
                <div class="form-group col-md-4">
                    <button type="submit" class="btn btn-primary">Rechercher</button>
                </div>
            </g:form>
            </br>
            <table class="table table-bordered table">
                <thead>
                <tr>
                    <g:sortableColumn class="field_text" property="username"
                                      title="Nom d'utilisateur" />
                    <g:sortableColumn class="field_text" property="enabled"
                                      title="Status" />
                    <g:sortableColumn class="field_text" property="Action"
                                      title="Action"/>
                </tr>
                </thead>
                <tbody>
                <g:if test="${userCount <= 0}">
                    <tr>
                        <td>Aucun.</td>
                        <td>Aucun.</td>
                        <td>Aucun.</td>
                    </tr>
                </g:if>
                <g:else>
                    <g:each in="${userList}" var="bean" status="i">
                        <tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
                            <td class="field_text">
                                <g:link method="GET" resource="${bean}">
                                    <p class="field_text">${bean.username}</p>
                                </g:link>
                            </td>
                            <td>
                                <div class="form-check form-switch">
                                    <g:if test="${user.id != bean.id}">
                                        <g:if test="${bean.enabled == false}">
                                                <input name="checkbox-${bean.id}" class="form-check-input enable-check" type="checkbox" id="flexSwitchCheckChecked">
                                                <label name="label-${bean.id}" class="form-check-label" style="display: flex; justify-content: space-around" for="flexSwitchCheckChecked">
                                                    <span class="badge badge-danger">Inactif</span>
                                                </label>
                                        </g:if>
                                        <g:if test="${bean.enabled == true}">
                                                <input name="checkbox-${bean.id}" class="form-check-input enable-check" type="checkbox" id="flexSwitchCheckChecked" checked>
                                                <label name="label-${bean.id}" class="form-check-label" style="display: flex; justify-content: space-around" for="flexSwitchCheckChecked">
                                                    <span class="badge badge-success">
                                                        Actif
                                                    </span>
                                                </label>
                                        </g:if>
                                    </g:if>
                                </div>
                            </td>
                            <td>
                                <g:link controller="User" action="edit" params="[id: bean.id]" class="btn btn-primary">
                                    Modifier
                                </g:link>
                                <g:if test="${user.id != bean.id}">
                                    <sec:ifAllGranted roles='ROLE_ADMIN'>
                                        <g:link controller="user" action="delete" params="[id: bean.id]"
                                                class="btn btn-danger exampleModal">
                                            Supprimer
                                        </g:link>
                                    </sec:ifAllGranted>
                                </g:if>

                            </td>
                        </tr>
                    </g:each>
                </g:else>
                </tbody>
            </table>

            <g:if test="${userCount > 0}">
                <div class="pagination">
                    <g:paginate params="${['searchkey':text,'status':status]}" total="${userCount ?: 0}" />
                </div>
            </g:if>
        </div>
    </body>
    <footer>
        <content tag="javascript">
            <script src="https://unpkg.com/@egoist/snackbar/dist/snackbar.min.js"></script>
            <script>
                function messageStatus(message, type){
                    var messageStatus = " <div class=\"alert alert-dark-"+type+" alert-dismissible fade show\" id=\"messageVal\">\n" +
                        "                     <button type=\"button\" class=\"close\" data-dismiss=\"alert\">×</button>\n" + message +
                        "                 </div>";
                    return messageStatus;
                }

                function spanBadgeStatus(status, type){
                    var span = "<span class=\"badge badge-"+type+"\">"+status+"</span>";
                    return span
                }

                $(".enable-check").on("click", function(){
                    var checked = $(this).prop('checked');
                    var name = $(this).prop('name');
                    var id = name.split('-')
                    var idUser = id[1]
                    var label = "label[name='label-"+idUser+"']"
                    var spanStatus = ""
                    if(checked){
                        console.log("checked true = "+checked)
                        $.ajax({
                            method: "GET",
                            url: "/projet/user/updateStatusUser",
                            data: { iduser: idUser, status: checked },
                            success: function (res) {
                                $(label).html('');
                                spanStatus = spanBadgeStatus("Actif", "success")
                                $(label).append(spanStatus)
                                snackbar.createSnackbar(res.message,{
                                    timeout: 3000
                                })
                            }
                        })
                    }
                    else{
                        console.log("checked false = "+checked)
                        $.ajax({
                            method: "GET",
                            url: "/projet/user/updateStatusUser",
                            data: { iduser: idUser, status: checked },
                            success: function (res) {
                                $(label).html('')
                                spanStatus = spanBadgeStatus("Inactif", "danger")
                                $(label).append(spanStatus)
                                snackbar.createSnackbar(res.message,{
                                    timeout: 3000
                                })
                            }
                        })
                    }
                })
            </script>
        </content>
    </footer>
</html>

grails-app/views/user/show.gsp
<%--
  Created by IntelliJ IDEA.
  User: Andi
  Date: 12/03/2021
  Time: 16:06
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta name="layout" content="main" />
    <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
    <title>Profil Utilisateur</title>
</head>

<body>
<div class="card mb-4">
    <h6 class="card-header">Profil Utilisateur</h6>
    <div class="card-body">
        <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
        </g:if>
            <div class="form-group">
                <label class="form-label">Nom d'utilisateur</label>
                <input type="text" class="form-control" placeholder="Email" value="${user.username}" name="username" disabled>
                <div class="clearfix"></div>
            </div>
            <div class="form-group">
                <label class="custom-control custom-checkbox">
                    <input type="checkbox" class="custom-control-input" ${user.enabled ? "checked" : "" } name="enabled" disabled>
                    <span class="custom-control-label">Activé</span>
                </label>
            </div>
            <div class="form-group">
                <label class="custom-control custom-checkbox">
                    <input type="checkbox" class="custom-control-input"  ${user.accountExpired ? "checked" : "" } name="accountExpired" disabled>
                    <span class="custom-control-label">Compte expiré</span>
                </label>
            </div>
            <div class="form-group">
                <label class="custom-control custom-checkbox">
                    <input type="checkbox" class="custom-control-input"  ${user.accountLocked ? "checked" : "" } name="accountLocked" disabled>
                    <span class="custom-control-label">Compte vérrouillé</span>
                </label>
            </div>
            <div class="form-group">
                <label class="custom-control custom-checkbox">
                    <input type="checkbox" class="custom-control-input"  ${user.passwordExpired ? "checked" : "" } name="passwordExpired" disabled>
                    <span class="custom-control-label">Mot de passe expiré </span>
                </label>
            </div>
            <g:link controller="user" action="edit" id="${user.id}">
                <button type="button" class="btn btn-primary">Modifier</button>
            </g:link>
    </div>
</div>

</body>
</html>